export const PHASE_MAPPING = {
	acquiring_lock: `Acquiring lock`,
	cycle_processing_failed: `Cycle processing failed`,
	cycle_processing_success: `Cycle processing success`,
	waiting_for_next_cycle: `Waiting for next cycle`,
	cycle_monitoring_canceled: `Cycle monitoring canceled`,
	failed_to_wait_for_next_completed_cycle: `Failed to wait for next completed cycle`,
	waiting_for_operator_action: `Waiting for operator action`,
	split_into_batches: `Splitting into batches`,
	execute_payouts: `Executing payouts`,
	check_conditions_and_prepare: `Checking conditions and preparing payouts`,
	generate_payout_candidates: `Generating payout candidates`,
	distribute_bonds: `Distributing bonds`,
	collect_baker_fee: `Collecting baker fee`,
	wait_for_sufficient_balance: `Waiting for sufficient balance`,
	check_sufficient_balance: `Checking sufficient balance`,
	collect_transaction_fees: `Collecting transaction fees`,
	validate_simulated_payouts: `Validating simulated payouts`,
	finalize_payouts: `Finalizing payouts`,
	create_blueprint: `Creating blueprint`,
	prepare_payouts: `Preparing payouts`,
	accumulate_payouts: `Accumulating payouts`,
	executing_batch: `Executing batch`,
	batch_execution_finished: `Batch execution finished`,
	batch_waiting_for_confirmation: `Batch waiting for confirmation`,
}